export const IMPORT_DATA = [
  {
    Id: 1,
    first_name: "Bobrowski",
    last_name: "Donald",
    email: "b@b.com",
    event_name: "test",
    dollarAmountOverride: 20,
    refferrer: "Robert",
    notes: "testing...",
    message: "Nothing",
  },
  {
    Id: 2,
    first_name: "jay",
    last_name: "may",
    email: "m@m.com",
    event_name: "test1",
    dollarAmountOverride: 13,
    refferrer: "Robert",
    notes: "testing....",
    message: "new",
  },
  {
    Id: 3,
    first_name: "Bobrowski1",
    last_name: "Bobrowski",
    email: "b@b.com",
    event_name: "copy",
    dollarAmountOverride: 30,
    refferrer: "Robert",
    notes: "copy",
    message: "copying",
  },
  {
    Id: 4,
    first_name: "d",
    last_name: "m",
    email: "n@n.com",
    event_name: "Bobrowski",
    dollarAmountOverride: 3,
    refferrer: "Robert",
    notes: "m.....",
    message: "no",
  },

];
